/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114988-g8c62d77139-20240424"
#endif /* AVUTIL_FFVERSION_H */
